### ISSUE TITLE
Using with react 0.14.0-beta

### ISSUE THREAD

**Issue by salzhrani** [Chrisui/react-hotkeys#11]
Peer dependency fails

**Comment by Chrisui** [comment]
What is the error message?

**Comment by salzhrani** [comment]
0.14.0-beta1 is not >= 0.12.2 ... I guess it should be fine when react is 0.14, for now it needs to be edited manually

**Comment by Chrisui** [comment]
I guess *-beta1* throws it off. Any idea what it can be changed to to allow that?

**Comment by salzhrani** [comment]
you could set the version to `>=0.12.2 || 0.14.0-beta1` but I guess you need to handle the deprecations beforehand

**Comment by mithrandi** [comment]
This is deliberate as a result of: https://github.com/npm/node-semver#prerelease-tags. I'm not sure exactly what the best way to resolve this is; maybe you could release a react-hotkeys with a prerelease version that has a dependency on react 0.14.0-beta1 or 0.14.0-rc1, then people could opt in to this version if they like?

**Comment by Chrisui** [comment]
I think that is a good idea. I will hopefully have some time tomorrow to
look at this if not it will be more like next week!

Crazy busy time at work atm :) but easing off soon giving us all time to
look at our open projects.

**Comment by mithrandi** [comment]
Meanwhile, React 0.14 final is out :)

**Comment by Chrisui** [comment]
Yup! Closing this for now.

Moving house this week but I have scheduled some time the following weekend to get out a largeish update featuring tests, support for HoCs & deprecating mixins while improving the internal usage of parent-child context.
