### ISSUE TITLE
Nested <HotKeys/>: owner-based and parent-based contexts differ

### ISSUE THREAD

**Issue by jeron-diovis** [Chrisui/react-hotkeys#13]
Just trying to repeat your [quick example](https://github.com/Chrisui/react-hotkeys/blob/master/README.md#quick-example).

Got this:
```
Warning: owner-based and parent-based contexts differ 
(values: `undefined` vs `[object Object]`) for key (hotKeyMap) 
while mounting Node 
(see: http://fb.me/react-context-by-parent)
```

I've simplified it to just two directly nested <HotKeys>, and same happens.
```jsx
const bar = () => console.log('this works');
const foo = () => console.log('this does not work');

<HotKeys keyMap={{foo: "q", bar: "w"}} handlers={{bar: bar }}>
            <HotKeys handlers={{foo: foo }}>
                    some plain text
            </HotKeys>
</HotKeys>
```

Gist by link from warning does not give for me any answers why exactly this happens and how to fix it, so I report this issue.

Using React 0.13.3

**Comment by Chrisui** [comment]
Hey @jeron-diovis.

This is expected until `0.14` lands and it's a warning you can safely ignore for now providing you're using the library as laid out in the "getting started" guide.

In 0.14 context use will be greatly simplified. https://github.com/Chrisui/react-hotkeys/blob/master/docs/getting-started.md#hotkey-map-context

If this is actually causing functional problems I'd be happy to look into it for you.

**Comment by jeron-diovis** [comment]
Shame on me, I missed this guide.
Indeed, using mixin did the trick. Thanks for pointing and for quick response.

Actually, while playing with it, I found out that nested hotkeys wasn't what I really need. I thought somehow that if I'll define a top-level HotKeys, then keyboard events, raised in it, will trigger handlers, defined in descendants. That is, I won't need to focus exact children to work with it's handlers (a kind of pubsub, actually).
While in practice nesting HotKeys only provides an additional abstraction layer between keycodes and business-logic's actions, nothing more.

Anyway, this lib is great. After introducing HOC it will become absolutely amazing, I think)

**Comment by Chrisui** [comment]
Cheers :)

I'm planning a large update which will bring up the library upto v1.0 when React v0.14 becomes stable to make the most of parent-based context and HoCs etc.
