### ISSUE TITLE
No hot keys in inputs?

### ISSUE THREAD

**Issue by vid** [chrisui/react-hotkeys#14]
I've set up hotkeys in a top level component. Within that are <input> elements. If I enter hotkeys in those elements they trigger. Is there a way to prevent that?

**Comment by Chrisui** [comment]
You will need to stop the key events bubbling up with
`event.stopPropagation()` on your input  or any intermediate component.

**Comment by vid** [comment]
OK. That adds a lot of overhead. Any way to add this through react-hotkeys globally?

**Comment by Chrisui** [comment]
You could have a generic `Input` component which implements this behaviour
by default maybe.  Or a `Form` component to catch the events higher even.

React is great for this kind of composition and abstraction.  :)

**Comment by vid** [comment]
True, but it seems to me other components shouldn't be concerned about hotkeys. 

One thing that is intuitive is to wrap my form components with another HotKeys with a keymap of {}. I tried this but it didn't work. Could this be a feature?

**Comment by Chrisui** [comment]
It's not really giving inputs any concept of hot keys but rather
generically on the event scope saying "I'm handling this event, nothing
else should unless I say explicitly"

Hotkeys will bubble to parents because applications will want to handle
different scopes.

Preventing hot keys triggered while a user is interacting with a specific
input is very much something that should be explicitly solved in
"userland".

**Comment by Chrisui** [comment]
Adding a prop to Hotkeys to act as some isolated container (preventing
Hotkey handling above) might be worth doing for some scenarios.

I'll have a further think about this.

**Comment by vid** [comment]
Thanks. I think without any facility like this, it is less of a drop in solution and more of a must-redesign-your-app-around-it thing.

**Comment by orlando** [comment]
@vid Old issue and you probably solved, but in case other are looking around on how to handle this globally you can use `Mousetrap.prototype.stopCallback`. This function receives an event and an element, and if it returns false, it will prevent the hotkey from being triggered.

You can check if the element is an input or a textarea and prevent the hotkey to be triggered returning false.

**Comment by ohde** [comment]
I have prevented it inside of 'inputs' using the following generic wrapper for handlers. (Which looks at the event.path)

```javascript
  preventInputFireEvent(run) {
    return (event) => {
      if (event.path[0].localName !== 'input') {
        event.preventDefault()
        run(event)
      }
    }
  }

  handlerWrapperPreventInputFireEvent(handler) {
    const newHandler = {}
    for (var key in handler) {
      if (handler.hasOwnProperty(key)) {
        newHandler[key] = this.preventInputFireEvent(handler[key])
      }
    }
    return newHandler
  }

<HotKeys keyMap={keyMap} handlers={this.handlerWrapperPreventInputFireEvent(handlers)}>
```

**Comment by chrisui** [comment]
Closing this issue in favour of https://github.com/chrisui/react-hotkeys/issues/31

For those looking for in-the-meantime solutions you can use `Mousetrap.stopCallback` or stop propagation of events from those elements you want isolated.

**Comment by slorber** [comment]
@chrisui can you explain how are we supposed to use Mousetrap.stopCallback with react-hotkeys plz?

**Comment by orlando** [comment]
@slorber https://craig.is/killing/mice#api.stopCallback. 

Put this somewhere in your code.

```js
Mousetrap.stopCallback = function (e, element, combo) {
  // stop for input, select, and textarea
  return element.tagName == 'INPUT' || element.tagName == 'SELECT' || element.tagName == 'TEXTAREA' || (element.contentEditable && element.contentEditable == 'true');
};
```
