### ISSUE TITLE
Warning about owner-based and parent-based contexts

### ISSUE THREAD

**Issue by gustavnikolaj** [Chrisui/react-hotkeys#15]
```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs
`[object Object]`) for key (hotKeyMap) while mounting HotKeys
(see: http://fb.me/react-context-by-parent)
```

I'm using ES6 classes with my react components. I get the warning above as soon as I have a <HotKeys> component within another <HotKeys> component. I've tried giving them both their own keyMap prop, but nothing seems to get rid of that warning.

Any clues?

**Comment by Chrisui** [comment]
Hey @gustavnikolaj 

This is something I'm aware and will be fixed with the next version (which I'll hopefully get time to write pretty soon) to work with React 0.14. For now you can simply ignore these warnings (sorry it's quite intrusive I know!) as everything will work fine (and should work fine after 0.14 upgrade if you plan on that).

See https://github.com/Chrisui/react-hotkeys/issues/13 for more details.

**Comment by gustavnikolaj** [comment]
Will updating to react 0.14.0-rc1 remove this warning, or does your library not yet support 0.14? :-)

**Comment by Chrisui** [comment]
There may just be some npm dependency issues as seen in
https://github.com/Chrisui/react-hotkeys/issues/11 but I haven't tried it
out so can't be sure.

Haven't had any time past few months to address but with 0.14 RC out now
going to try and make some time in coming weeks!

Always open to a PR if the dependency issue could be fixed for now :)



On Sun, Sep 13, 2015 at 12:39 PM, Gustav Nikolaj <notifications@github.com>
wrote:

> Will updating to react 0.14.0-rc1 remove this warning, or does your
> library not yet support 0.14? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Chrisui/react-hotkeys/issues/15#issuecomment-139862796>
> .
>



-- 
*Chris Pearce - **Front-end Developer*

http://chrispearce.co

**Comment by Chrisui** [comment]
Other than that it should all work just fine.

On Sun, Sep 13, 2015 at 12:41 PM, Christopher Pearce <hello@chrispearce.me>
wrote:

> There may just be some npm dependency issues as seen in
> https://github.com/Chrisui/react-hotkeys/issues/11 but I haven't tried it
> out so can't be sure.
>
> Haven't had any time past few months to address but with 0.14 RC out now
> going to try and make some time in coming weeks!
>
> Always open to a PR if the dependency issue could be fixed for now :)
>
>
>
> On Sun, Sep 13, 2015 at 12:39 PM, Gustav Nikolaj <notifications@github.com
> > wrote:
>
>> Will updating to react 0.14.0-rc1 remove this warning, or does your
>> library not yet support 0.14? :-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Chrisui/react-hotkeys/issues/15#issuecomment-139862796>
>> .
>>
>
>
>
> --
> *Chris Pearce - **Front-end Developer*
>
> http://chrispearce.co
>



-- 
*Chris Pearce - **Front-end Developer*

http://chrispearce.co

**Comment by gustavnikolaj** [comment]
I couldn't get your tests running. `Error: Cannot find module 'react/addons'`. I'm not doing a lot of react stuff, so I'd prefer having working tests and decent test coverage, should I do any work on it :-) I'll wait patiently on a fix ;-)

**Comment by Chrisui** [comment]
Closing this now 0.14 is out.

See: https://github.com/Chrisui/react-hotkeys/issues/11
