### ISSUE TITLE
undefined: TypeError: undefined is not an object (evaluating 'this.__mousetrap__.reset')

### ISSUE THREAD

**Issue by stevewillard** [Chrisui/react-hotkeys#18]
Sometimes when switching between mounting/unmounting components I get the following error. Has anyone seen this before? I'm using react-hotkeys 0.5.0 and react 0.13.3 w/ react-router 0.13.3

```Uncaught TypeError: Cannot read property 'reset' of undefineds.default.createClass.componentWillUnmount @ HotKeys.js:107x.unmountComponent @ ReactCompositeComponent.js:273o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56s.unmountChildren @ ReactChildReconciler.js:119b.Mixin.unmountChildren @ ReactMultiChild.js:329a.Mixin.unmountComponent @ ReactDOMComponent.js:481o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56s.unmountChildren @ ReactChildReconciler.js:119b.Mixin.unmountChildren @ ReactMultiChild.js:329a.Mixin.unmountComponent @ ReactDOMComponent.js:481o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56s.unmountChildren @ ReactChildReconciler.js:119b.Mixin.unmountChildren @ ReactMultiChild.js:329a.Mixin.unmountComponent @ ReactDOMComponent.js:481o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56s.unmountChildren @ ReactChildReconciler.js:119b.Mixin.unmountChildren @ ReactMultiChild.js:329a.Mixin.unmountComponent @ ReactDOMComponent.js:481o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56x.unmountComponent @ ReactCompositeComponent.js:279o.unmountComponent @ ReactReconciler.js:56x._updateRenderedComponent @ ReactCompositeComponent.js:758x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97s.updateChildren @ ReactChildReconciler.js:83b.Mixin._updateChildren @ ReactMultiChild.js:277b.Mixin.updateChildren @ ReactMultiChild.js:251a.Mixin._updateDOMChildren @ ReactDOMComponent.js:470a.Mixin.updateComponent @ ReactDOMComponent.js:319a.Mixin.receiveComponent @ ReactDOMComponent.js:303o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x._updateRenderedComponent @ ReactCompositeComponent.js:748x._performComponentUpdate @ ReactCompositeComponent.js:726x.updateComponent @ ReactCompositeComponent.js:642x.receiveComponent @ ReactCompositeComponent.js:506o.receiveComponent @ ReactReconciler.js:97x.performUpdateIfNecessary @ ReactCompositeComponent.js:524o.performUpdateIfNecessary @ ReactReconciler.js:115s @ ReactUpdates.js:151i.perform @ Transaction.js:134i.perform @ Transaction.js:134m.perform @ ReactUpdates.js:95k @ ReactUpdates.js:175M.close @ ReactUpdates.js:51i.closeAll @ Transaction.js:207i.perform @ Transaction.js:148m.perform @ ReactUpdates.js:95k @ ReactUpdates.js:175i.closeAll @ Transaction.js:207i.perform @ Transaction.js:148d.batchedUpdates @ ReactDefaultBatchingStrategy.js:66o @ ReactUpdates.js:110b.dispatchEvent @ ReactEventListener.js:174```

**Comment by Chrisui** [comment]
I have seen this error occasionally when working with hotkeys on our app but it's never caused anything to break as it runs in a separate event loop for us. Is this causing any breakages for you or just an ugly error at the moment?

Seems really odd to me that the instance is not available in `componentWillUnmount` if the lifecycle methods are firing in order. Could possible be linked with https://github.com/facebook/react/issues/2410

**Comment by stevewillard** [comment]
It's causing a breakage, where React gets into a bad state. I think it might have something to do with server side rendering.... but I'm not sure because it's kind of difficult to reproduce. I'll do more testing and come back with more information.

**Comment by stevewillard** [comment]
Is there any way you could add a check for `this.__mousetrap__` when you do this `this.__mousetrap__.reset();`

in `componentWillUnmount`? I'm seeing this blow up when switching quickly between some nav items and rendering content below. Maybe componentDidMount never gets called?

**Comment by Chrisui** [comment]
Yeah, I will do this. Was just holding off hoping to find a reproducible
case to find the root cause rather than stick in a safety check.

Will get this done and published  tonight :)

**Comment by stevewillard** [comment]
Thanks! I will keep working towards figuring out the root problem.

**Comment by Chrisui** [comment]
Just published v0.7.0 :)
