### ISSUE TITLE
Entirety of react-dom is included in hotkeys

### ISSUE THREAD

**Issue by gavinmillar** [chrisui/react-hotkeys#34]
The webpack excludes doesn't list react-dom and therefore the outputted JS includes all of it. This results in a minified JS size of ~150kB. Simply adding react-dom to excludes reduces the output size to 18kB.

Would it be reasonable to make the assumption that react-dom is already available rather than including it here as well?

**Comment by gavinmillar** [comment]
I've made a PR for this if you wish to take it, apologies that I didn't link the two together.
https://github.com/chrisui/react-hotkeys/pull/35

**Comment by chrisui** [comment]
Thanks for the report and PR! :) This is released with `v0.9.0` and is available for download from the repo.
