### ISSUE TITLE
Unknown props warning

### ISSUE THREAD

**Issue by enginehenryed** [chrisui/react-hotkeys#36]
React issues a warning saying "Unknown props `keyMap`, `handlers`, `component` on <div> tag. Remove these props from the element."

Seems like we should exclude or explicitly distinguish properties in 'this.props' when passing/getting it into/from other components.

**Comment by mattkrick** [comment]
Worth noting that this pops up due to changes in react 15.2.

Error message looks something like this:
![screen shot 2016-07-18 at 11 31 04 am](https://cloud.githubusercontent.com/assets/5514175/16925965/8edeaef6-4cdb-11e6-9950-84deab7046e8.png)

Will PR in a bit

**Comment by chrisui** [comment]
Have released a fix for this with `v0.9.0`. Thanks!

Release diff: https://github.com/chrisui/react-hotkeys/compare/v0.8.0...v0.9.0?expand=1
