### ISSUE TITLE
Is this project dead completely?

### ISSUE THREAD

**Issue by colmbrady** [chrisui/react-hotkeys#37]
Its seems that there is little response to any support issues raised on this project.

Is there any intent to keep this project going?

Do you need help with supporting this?

My company needs to supports keyboard navigation and high levels of accessibility so we see the value in a framework helping to manage that aspect. We are currently evaluating whether to continue to use this component, but if we cant get P.Rs accepted to fix bugs, its makes us unlikely to want to continue using it.

Would appreciate some information on where this repo is heading. If the burden of supporting this is to much we may fork this and enhance it internally. Thanks.

**Comment by chrisui** [comment]
Sorry for the lack of response!

I've literally just landed after a prolonged holiday so have not been
watching any of the activity here over the past month or so. I will be
responding over the next couple of days and getting prs merged.

As for further contribution I will not have time to work on the proposed v1
Roadmap (mainly just modernising and consolidatiny apis) and welcome anyone
who wants to jump on that.

**Comment by colmbrady** [comment]
Thanks Chris. Good to hear.

**Comment by chrisui** [comment]
Done a clean of issues and pull requests. `v0.9.0` is now published to npm and UMD build available from repo.

Thanks for a nudge! :)
