### ISSUE TITLE
Add change log file or release note

### ISSUE THREAD

**Issue by nhducit** [chrisui/react-hotkeys#38]
Please add change log file or release note for every release version. It provides new features were added and breaking changes were produced in a release version and help developers update to newer versions smoothly

**Comment by chrisui** [comment]
👍

**Comment by chrisui** [comment]
Will be keeping on top of this going forwards.

NB. Hoping to transfer ownership of this project into my company so we can have an active team maintain it as day-to-day rather than being a neglected project on the side.
