### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by chrisui** [chrisui/react-hotkeys#4]

**Comment by Chrisui** [comment]
Hopefully get to this soon. Very busy atm and wanted to focus any time I did manage on fixing the propagation issue and making sure this badboy is ready for usage in the real world. (think the only major thing left is the optimisation of moustrap delegation)

Tests are ready to be written with mocha and a jsdom environment.

**Comment by greena13** [comment]
Added the start of a test suite in #52a5bdc
