### ISSUE TITLE
Reactiflux slack support link broken

### ISSUE THREAD

**Issue by Nesciosquid** [chrisui/react-hotkeys#43]
Your link to the reactiflux Slack group on the Readme seems to be broken! :(

**Comment by chrisui** [comment]
Ah, reactiflux is no longer on slack but is on discord. Shall address that!

If you need some help I can try and lend a hand via this issue?

**Comment by Nesciosquid** [comment]
I'm good so far! Was just clickin' around to get a sense of things before I install. Thanks. <3
