### ISSUE TITLE
Focus Trap uses depreciated React.createClass 

### ISSUE THREAD

**Issue by aepyornis** [chrisui/react-hotkeys#57]
React v15.5 has [depreciated React.createClass](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html). [This line](https://github.com/chrisui/react-hotkeys/blob/master/lib/FocusTrap.js#L3) raises a warning while using react-hotkeys: " Warning: FocusTrap: React.createClass is deprecated and will be removed in version 16"

**Comment by oltodo** [comment]
Fixed in the [0.10.0](https://github.com/chrisui/react-hotkeys/commit/6bcadd69f791d5ebae02e0ad9b584d42cc455e6a) right?

**Comment by aepyornis** [comment]
yes. thank you!
