### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [chrisui/react-hotkeys#6]
Unless one exists, have not seen. Would like to add to react.rocks -- thanks

**Comment by Chrisui** [comment]
There's a very basic one you can run in /examples/master which was just something I was messing with during initial development but I will work on something a bit fancier this evening!

**Comment by Chrisui** [comment]
I've *started* a [demo](http://chrisui.github.io/react-hotkeys/) which you can see the source for [here](https://github.com/Chrisui/react-hotkeys/blob/master/examples/master/index.js).

It's highlighted an issue with the current implementation that I'd like to fix before finishing off the demo so maybe hold off on submission to anywhere :)

**Comment by Chrisui** [comment]
Issues fixed (v0.2.0 published)

Can have a play here: http://chrisui.github.io/react-hotkeys/

Ugly as hell still and probably not the most accessible! Got what I could with the time available to me (ie. with job hunting, moving house etc.).

PR's always welcome and for that reason I'll leave this issue open for visibility on that little request! :)

**Comment by chrisui** [comment]
Closing to tidy.

Still always open to prettier demos! ;)

**Comment by winkler1** [comment]
👍 gets the job done! https://react.rocks/example/react-hotkeys
