### ISSUE TITLE
Broken on React 16

### ISSUE THREAD

**Issue by natew** [chrisui/react-hotkeys#67]
Just upgraded and spent some time walking through and trying to find where this is breaking. To be honest I'm not totally sure.

It does seem to be calling updateHotKeys a ton.  Not sure why but it looks like it runs it as it's pushing each shortcut into an array, or something along these lines. Very strange but [if I put a debugger here](https://github.com/chrisui/react-hotkeys/blob/cf06fed4089e59d69df9f01248ef4c86614cc69e/lib/HotKeys.js#L132) it actually gets called once for every shortcut I define, as though it's building an array of them one by one and then calling this function each time.

Not sure if that's it. I tested manually by creating my own little mousetrap thing and it works fine, so it's not mousetrap. I don't see anything else obvious that would cause this break though.

**Comment by tim-soft** [comment]
I've noticed similar behavior and wasn't able to narrow it down, hopefully someone with more knowledge can come in with a fix

**Comment by sapegin** [comment]
I’ve updated an example to React 16 and it works fine, maybe it’s broken for some particular use case. Please have a look at the PR: #71.

**Comment by greena13** [comment]
@natew is this still an issue with the final release of React 16?

**Comment by greena13** [comment]
Closing for now. Please let me know if this is still an issue.
