### ISSUE TITLE
arrow keys don't work

### ISSUE THREAD

**Issue by aroman** [chrisui/react-hotkeys#68]
Even with the correct key name like 'ArrowUp'. other keys (e.g. 'r') work.

**Comment by vivian-eb** [comment]
are you using keydown or keypress

**Comment by aroman** [comment]
Keypress

**Comment by vivian-eb** [comment]
Keydown captures ArrowKeys and other non-printable keys (i.e. Enter), could you try that instead?

**Comment by aroman** [comment]
thanks so much!
