### ISSUE TITLE
New Maintainer/Owner Request

### ISSUE THREAD

**Issue by chrisui** [chrisui/react-hotkeys#72]
Hey there!

I simply no longer have (read: never really have gad) the time or incentive to maintain and take forward this project. 

I'm happy to hand over the reigns to anyone who will be able to modernise the project and help respond to the small amount of requests that come in.

If you're interested please comment below! And sorry to everyone relying on this project who has not been able to update to the latest React.

Chris

**Comment by greena13** [comment]
I am interested in helping out.

**Comment by chrisui** [comment]
@greena13 I'll add you as a contributor and if no one else is interested in coming weeks will then transfer ownership over!

**Comment by greena13** [comment]
Sounds good. Anything I should know before I get started?

**Comment by greena13** [comment]
I believe I will also need npm permission to push new versions if I am to effectively maintain this package.

**Comment by weihanglo** [comment]
I am willing to contribute. Where should I  get started? Maybe upgrade codebase to new React version?

**Comment by greena13** [comment]
Hey weihanglo, it would be great to have you help get the package up to date.

I was planning on trying to resolve the outstanding pull requests before attempting to update the package to the new React version to reduce merge conflicts and include the new functionality separate of upgrading React in case people who are using the older version of React need or want it.

I've sent you a message on www.gitter.im so we can discuss further.

**Comment by sapegin** [comment]
@greena13 @weihanglo Please take a look at my PR that does just that: #71.

**Comment by chrisui** [comment]
Going to transfer over to @greena13 now and they can take from there. Thanks so much all for getting involved!

Getting the package modernised and compatible with newer environments/React etc would be a great start.

@greena13 are you on npm under the same username?

**Comment by greena13** [comment]
Yes, I use the same username on npm.

**Comment by Heedster** [comment]
@chrisui @greena13 I would like to help out.

**Comment by greena13** [comment]
Your contributions would be very welcome, @Heedster. I think gitter https://gitter.im/chrisui/react-hotkeys makes the most sense for general coordination going forward. Please log in and we can figure out who can do what, next.

**Comment by greena13** [comment]
Closing this now as maintenance has started to pick up speed. If you are interested in contributing or helping managing this package, your very, very welcome to. Please checkout [the project's gitter](https://gitter.im/chrisui/react-hotkeys) or take a look [the list of open issues](https://github.com/chrisui/react-hotkeys/issues) and [list of Projects](https://github.com/chrisui/react-hotkeys/projects) to see if you can find something you're interested in tackling.

**Comment by greena13** [comment]
@chrisui, I missed the request to transfer ownership of the repo (a 24 hour timeout seems a little short to me). Could you please send it again and let me know here when you have, to increase the chances of me seeing it in time.

**Comment by chrisui** [comment]
@greena13 restarted the request! :)
